version: "3.7"

services: 
    mssql:
        build: ./Db
        ports:
            - 1433:1433

    planning-poker:
        build: .
        restart: always
        env_file:
            - env.list
        ports:
            - 80:8080
        depends_on:
            - mssql
    