version: "3.7"

services: 
    mssql:
        build: ./Db
        ports:
            - 1433:1433
        networks:
            - planning-poker-network
            
    planning-poker:
        build: .
        restart: always
        env_file:
            - env.list
        ports:
            - 80:8080
        networks:
            - planning-poker-network
        depends_on:
            - mssql
              
networks:
    planning-poker-network:
        name: planning-poker
        
    
    